// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdsrgutbwxajmkywdpny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkc3JndXRid3hham1reXdkcG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NzczMDIsImV4cCI6MjA4OTI1MzMwMn0.l4-r_BGHAwqU5_OD5-TSz3bWhwXK4A3yy-EVaq4_sjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});